plugins:
  - jekyll-seo-tag
  - jekyll-postcss

author: "Oscar Franco"
url: "https://messerapp.cc"
title: "Messer -- macOS app for local image conversion and optimization"
description: "macOS menubar app to resize and convert images"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - README.md
  - postcss.config.js
  - .gitignore
