author: "Oscar Franco"
url: "https://messerapp.cc"
title: "Messer -- macOS app for image conversion and optimization"
description: "macOS menubar app to resize and convert images"

plugins:
  - jekyll-seo-tag
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - README.md
  - .gitignore
