author: "Oscar Franco"
url: "https://messerapp.cc"
title: "Messer -- convert, resize and edit images with native macOS menu bar app"
description: "convert, resize and edit images with native macOS menu bar app"

plugins:
  - jekyll-seo-tag
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - README.md
  - .gitignore
